### PR TITLE
LPS-84043: SF

### PR DESCRIPTION
**Pull request by renatodepaiva**

### CODE REVIEW

**Comment by renatodepaiva** [comment]
ci:test:sf

**Comment by renatodepaiva** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by renatodepaiva** [comment]
ci:test:relevant

**Comment by renatodepaiva** [comment]
Pull request forwarded to https://github.com/robertoDiaz/liferay-portal/pull/720. [See changes here.](https://github.com/renatodepaiva/liferay-portal/compare/a9571292165e~5...a9571292165e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
