### PR TITLE
LPS-84043 Consistency: Apply to more cases

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @renatodepaiva 

could you check if I broke something with my changes??

thanks!!

**Comment by robertoDiaz** [comment]
@renatodepaiva 

Once you have test it, please resend it to me to move it forward.

Thanks!!

**Comment by renatodepaiva** [comment]
Will do @robertoDiaz! As soon as I test it I will let you know.

**Comment by renatodepaiva** [comment]
Sent you a new pull request with the modifications: https://github.com/robertoDiaz/liferay-portal/pull/720#issuecomment-412495319

**Pull request closed without merging**
